language: java
jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

addons:
  sonarcloud:
    organization: "nikolas-charalambidis"
    token: "oK3dWY3UwnVgOLTSEMpaZzubIbYHN3vJnOWLfN9f/7fB9RW6Q/YqWp0L4N5oFH5uGLvdreG55RW8MoTe6F4ODQbKGHnoCIru2tVnFYHxw0R9u62wEY04rbrLsJxAZSv7cEgQ+AsS6nTPcus6itgHQIQ8h6vaqdjSy3PRN85AF2znm+VHscnkWGMoP6rw/IZACQZMtoWY5Aaf/YjVqH6IVJu5+bVhu2hBgOmvQWoSg3VXihRsXk6YjFJxZYy+vPkvgduWEO2EST0kT/cdrHG6gdnwqfO30vIlWk+VoEUc1kuXNlNI+D3CKtalvnOosZr7jHnk8sO+XWEq03L0l1IDRbfD6T01dk4siGz36BX47lxrJBDS9ss+eMDftWA9nDVagnRWmyyyWCQvHQ06ZftjyDfWtFFBxY7WLkkTBJ/QMVFdZfOWJsDrwzmg+W1hjkfW7HTuSTa/UHEUdKIKZUhkkwsfGvROSJTm7m9BufhTAyvVrDmq/lBErk1PPTDF8JMhbNODpW4ETA5o0xKyI9nMMJqm0wPXQJei+gN7IGJ2B3WdJnoGDLZ7hBEaQugv7pxWGjORRXV48LgoB5YcrMOf9aatC5iTkpfXLyBq4u9q4uoYmjL5702aVT4pnYNJq0AJXmGDhL0cBL82a8DcakGhofOi7yUhSKNOjdlwCqnBdqM="

before_install:
  - chmod +x mvnw

install: true
script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Nikolas-Charalambidis_interview-land-routes
