language: java
jdk: openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: nikolas-charalambidis
    token:
      secure: jIGoO1WbtHjqwH0K3eP/VVHxVoDGQyvbfeojcrliUKmISakVqDhP48ugIueLmE9tCHIYMJ4osKTeDYYke8PC6cLVCuujXjoV65FyVvI4fAb8JXEY8OIgka35rnICdDBMSCxZe4mz7+o6gdE1eeiji2PZYXDarchtCkgdoMwTF6fPGBNP2mLs+6exoeQlpSgGQnrbEp/BoxTkP/B179bXO5bi+JkkEcwAhaXaYRNsW1vaot0JDjkfHhXKsZ+fSFIVnSnfHUj2U0fwBjBAKw2DvRN2ItgiQlwZX0CnPNE2pXjaLoQ5sX3gYNl+LoI/KMM0iknnz/qfGbImJqSuc1HSq38wCISgcVbJVUvjbYX2k0wSRfr7xHAAUEWyX7GqAlO6/32rOgcKQKK2VtwfOMWdv4y+gPDxhtUggs84XyWQTtDjG1DO8KOT16dIQ4sjmuTRE3QhLxU2luqecGeETUGYCQdmRrXjFOUg9k6Dnu/f+RswtfMkrkjeruUFY9eCvkvp0f2QgF6U81VhemOWTxV5K9wQ4lx7McOPoNLnKsZXNBvae5da6gpqePZVY3V/8yh+NJSw87o4nvVIClYWtB5tSaMTkMR2c3y+l6ypW5GzJfOLCQTYGR+VeSTLqwWE4+yzIi2hHqlXWuprdBfrGeBVRZac+LRiS8LaUlqlPFj9fHM=

before_install:
  - chmod +x mvnw

install: true

script: "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Nikolas-Charalambidis_interview-land-routes"
