language: java
jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

addons:
  sonarcloud:
    organization: "nikolas-charalambidis"
    token:
      secure: "V1bxWrv7Hk9VSn4Vr7EPqNwPpqT2uQZWMoA2113iS1qqiAI3kMZMwNjqtI1dusTcTrkHQ9efABLpWl7HYk4V8r2srMZBxl2+fQYv0F1YTMvYPvbJbQ/QmnbIptBTz3ZFbGcLJRLa1+Ybuxbc9YN/1ymKq3VS8CXknVrb5YVrqt0D8eX4gZ85afSTwTbbz1a+tovCTPyAIoRhCHT+X/Yd1+mCHPHvoRyHzSrlkSZjc8pHbtJLAKX9OFqisr7TDpwwD2AL5052c1qP7t7mYD5ytwvZbRIpMO3uMckWvcKkOfBE5lZ3XlMcORBTKAdeOGvLMHRtWV2U4QcLWxFWmlsVkMYfPHJsIe8Bnatb7aABXGek4KElzuJ57O2uOUk/O5RjlwI247pUzESa/UxzEMqk7XXsc2V5ZwjTNWEWI1LRkoVMLjViBzKBfLKZPHtXbE8WJn/CJjDNKXRzBV0N0sPl6Sx0r6hsHrLMmR5OEKf6uBYTr1LY92XfOEJoVXy10aZfmAQaV5AHoxkSQWOJxGK2+ezEIn/2kuaIcfyN3eu3Yj07s3AaJdyQmzZb5RL7YlChVKDMunLyiP6lyJ80AsmegV/+Lr8xjOaWEW0Ub4maejRh/lJrD5t8KSIAlDxzqkEA0Ko6KOXrSwvQBtAS9R5dZ0neMyJdP9KeMxdc3Dkk/EM="

before_install:
  - chmod +x mvnw

install: true
script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=interview-land-routes